input:
    points: ./data/stations.csv
    ldd_fine: ../MERIT/dir_danube_3sec.tif
    upstream_fine: ../MERIT/upa_danube_3sec.tif
    ldd_coarse: ./data/ldd_European_01min.nc
    upstream_coarse: ./data/upArea_European_01min.nc
            
output_folder: ./results/

conditions:
    min_area: 100 # km2
    abs_error: 50 # km2
    pct_error: 1 # %